a_toggle <- function(...) a(style = "text-decoration: underline;", ...)
transform_helpText <- function(var = "x") {
  div(
  helpText(style = "font-size: 13px;", 
           "To apply a transformation, provide a function of x",
           if (var != "x") "(or y or z)",
           "in the box below and then click", code("Transform")),
  helpText(style = "font-size: 10px;", 
           "Most valid R expressions will work, e.g.,",
           paste0('log(', var,')'), paste0('sqrt(', var,')'),
           paste0('exp(', var,'/100)'), paste0('1/(1+exp(-', var,')),'), "etc."
           )
  )
}

# function to suppress unnecessary warnings and messages generated by ggplot 
suppress_and_print <- function(x) suppressMessages(suppressWarnings(print(x)))

# make_param_list ------------------------------------------------------
# generate list of parameter names (formatted for shiny::selectInput)
.make_param_list <- function(object) {
  param_groups <- names(object@param_dims)
  choices <- list()
  ll <- length(object@param_dims)
  choices[1:ll] <- ""
  names(choices) <- param_groups
  for(i in 1:ll) {
    if (length(object@param_dims[[i]]) == 0) {
      choices[[i]] <- list(param_groups[i])
    }
    else {
      temp <- paste0(param_groups[i],"\\[")
      choices[[i]] <- object@param_names[grep(temp, object@param_names)]
    }
  }
  choices
}

# make_param_list_with_groups ------------------------------------------------------
# generate list of parameter names  and include parameter groups (formatted for shiny::selectInput)
.make_param_list_with_groups <- function(object, sort_j = FALSE) {
  choices <- list()
  param_groups <- names(object@param_dims)
  ll <- length(object@param_dims)
  LL <- sapply(1:ll, function(i) length(object@param_dims[[i]]))
  
  choices[1:ll] <- ""
  names(choices) <- param_groups
  for(i in 1:ll) {
    if (LL[i] == 0) {
      choices[[i]] <- list(param_groups[i])
    } else {
      group <- param_groups[i]
      temp <- paste0("^",group,"\\[")
      ch <- object@param_names[grep(temp, object@param_names)]
      
      #       toggle row/column major sorting so e.g. "beta[1,1], beta[1,2],
      #       beta[2,1], beta[2,2]" instead of "beta[1,1], beta[2,1], beta[1,2],
      #       beta[2,2]"
      if (sort_j == TRUE & LL[i] > 1) ch <- gtools::mixedsort(ch) 
      
      ch_out <- c(paste0(group,"_as_shiny_stan_group"), ch)
      names(ch_out) <- c(paste("ALL", group), ch)
      choices[[i]] <- ch_out
    }
  }
  
  choices
}

# update_params_with_groups -----------------------------------------------
# update parameter selection for multi-parameter plots
.update_params_with_groups <- function(params, all_param_names) {
  as_group <- grep("_as_shiny_stan_group", params)
  if (length(as_group) == 0) return(params)
  
  make_group <- function(group_name) {
    all_param_names[grep(paste0("^",group_name,"\\["), all_param_names)]
  }
  single_params <- params[-as_group]
  grouped_params <- params[as_group]
  groups <- gsub("_as_shiny_stan_group", "", grouped_params)
  groups <- sapply(groups, make_group)
  updated_params <- c(single_params, unlist(groups))
  updated_params
}


color_vector <- function(n) {
  hues = seq(15, 375, length=n+1)
  hcl(h=hues, l=50, c=50)[1:n]
}
color_vector_chain <- function(n) {
  hues = seq(15, 375, length=n+1)
  hcl(h=hues, l=80, c=50)[1:n]
}

# ggplot theme elements to be used as needed  -----------------------------
blue_color <- "#006dcc"
theme <- function(...) ggplot2::theme(...)
transparent <- theme(panel.background = element_blank(), plot.background = element_blank())
axis_line_color <- "gray20"
axis_color <- theme(axis.line = element_line(color = axis_line_color))
axis_labs <- theme(axis.title = element_text(face = "bold", size = 13))
title_txt <- theme(plot.title = element_text(face = "bold", size = 14))
fat_axis <- theme(axis.line.x = element_line(size = 3, color = axis_line_color), 
                  axis.line.y = element_line(size = 0.5, color = axis_line_color))
h_lines <- theme(panel.grid.major = element_line(size = 0.10, linetype = 3, color = "turquoise4"),
                 panel.grid.major.x = element_blank())
v_lines <- theme(panel.grid.major = element_line(size = 0.25, linetype = 3, color = "turquoise4"),
                 panel.grid.major.y = element_blank())
no_lgnd <- theme(legend.position = "none")
lgnd_bot <- theme(legend.position = "bottom", legend.background = element_blank())
lgnd_top <- theme(legend.position = "top", legend.background = element_blank())
lgnd_left <- theme(legend.position = "left", legend.background = element_blank())
lgnd_right <- theme(legend.position = "right", legend.background = element_blank())
no_yaxs <- theme(axis.line.y = element_blank(), axis.ticks.y = element_blank(), axis.text.y = element_blank())
strip_txt <- theme(strip.text = element_text(size = 12, face = "bold", color = "white"),
                   strip.background = element_rect(color = axis_line_color, 
                                                   fill = axis_line_color))

base_fill <- "#66a7e0" 
overlay_fill <- "#006dcc" 
vline_base_clr <- "#006dcc"
pt_outline_clr <- "#328ad6"
# vline_overlay_clr <- "black"
divergent_fill <- "#ae0001" # "#5cffcc"
hit_max_td_fill <- "#eeba30"
divergent_clr <-  "black" #"#772000" # "#40b28e"
hit_max_td_clr <- "black" # "#473600"
div_and_hit_shape <- 21



# probability distributions -----------------------------------------------

# other functions ---------------------------------------------------------
inv_logit <- invlogit <- function(x) {
  1/(1 + exp(-x))
}
logit <- function(x) log(x / (1-x))
