# function to suppress unnecessary warnings and messages generated by ggplot 
suppress_and_print <- function(x) {
  suppressMessages(suppressWarnings(print(x)))
}

# Create help text for video tab in Explore

knitr::knit('markdown/about_video.Rmd',output='markdown/about_video.md',quiet=TRUE)

# Set animation options for animation package

animation::ani.options(ani.height=1000,ani.width=1200,plot_res=200)

# Need to patch the saveVideo function from animation to allow the use of custom animation

in_dir <- function (wd, expr) 
{
  owd = setwd(wd)
  on.exit(setwd(owd))
  expr
}

saveVideo = function(
  expr, video.name = 'animation.mp4', img.name = 'Rplot', ffmpeg = animation::ani.options('ffmpeg'),
  other.opts = if (grepl('[.]mp4$', video.name)) '-pix_fmt yuv420p', ...
) {
  oopt = animation::ani.options(...)
  on.exit(animation::ani.options(oopt))
  
  if(!dir.exists(dirname(video.name))){
    dir.create(dirname(video.name))
  }
  
  owd = setwd(tempdir())
  on.exit(setwd(owd), add = TRUE)
  
  # default ffmpeg command to 'ffmpeg' if not specified
  if (is.null(ffmpeg)) {
    ffmpeg = 'ffmpeg'
  }
  if (!grepl('^["\']', ffmpeg)) ffmpeg = shQuote(ffmpeg)
  
  version = try(system(paste(ffmpeg, '-version'), intern = TRUE))
  if (inherits(version, 'try-error')) {
    warning('The command "', ffmpeg, '" is not available in your system. Please install FFmpeg or avconv first: ',
            ifelse(.Platform$OS.type == 'windows', 'http://ffmpeg.arrozcru.org/autobuilds/',
                   'http://ffmpeg.org/download.html'))
    return()
  }
  
  ani.dev = animation::ani.options('ani.dev')
  file.ext = animation::ani.options('ani.type')
  interval = animation::ani.options('interval')

  if (is.character(ani.dev)) ani.dev = get(ani.dev)
  
  num = ifelse(file.ext == 'pdf', '', '%d')
  unlink(paste(img.name, '*.', file.ext, sep = ''))
  img.fmt = paste(img.name, num, '.', file.ext, sep = '')
  img.fmt = file.path(tempdir(), img.fmt)
  animation::ani.options(img.fmt = img.fmt)
  if ((use.dev <- animation::ani.options('use.dev')))
    ani.dev(img.fmt, width = animation::ani.options('ani.width'),
            height = animation::ani.options('ani.height'),res=animation::ani.options('plot_res'))
  in_dir(owd, expr)
  if (use.dev) dev.off()
  
  ## call FFmpeg
  ffmpeg = paste(ffmpeg, '-y', '-framerate', 1/animation::ani.options('interval'), '-i',
                 basename(img.fmt), other.opts, basename(video.name))
  message('Executing: ', ffmpeg)
  cmd = system(ffmpeg)
  
  if (cmd == 0) {
    setwd(owd)
    if(!grepl(tempdir(),video.name,fixed = T))
      file.copy(file.path(tempdir(), basename(video.name)), video.name, overwrite = TRUE)
    message('\n\nVideo has been created at: ',
            output.path <- normalizePath(video.name))
    #auto_browse(output.path)
    
  }
  invisible(cmd)
}

animation_saver <- function(saver, filename, mime_type = NULL) {
  if (is.function(saver)) {
    return(list(func = saver, mime_type = mime_type))
  }
  if (is.null(saver)) {
    saver <- tolower(tools::file_ext(filename))
  }
  savers <- list(gif = animation::saveGIF,
                 mp4 = saveVideo,
                 webm = saveVideo,
                 avi = animation::saveVideo,
                 html = function(expr, filename, ...) animation::saveHTML(expr, htmlfile = filename, ...),
                 tex = function(expr, filename, ...) animation::saveLatex(expr, latex.filename = filename, ...),
                 pdf = function(expr, filename, ...) animation::saveLatex(expr, latex.filename = gsub("pdf$", "tex", filename, perl = TRUE)),
                 swf = animation::saveSWF)
  
  if (is.null(savers[[saver]])) {
    stop("Don't know how to save animation of type ", saver)
  }
  
  # for those that can be viewed in RStudio, save the mime_type
  mime_types <- list(gif = "image/gif",
                     mp4 = "video/mp4",
                     webm = "video/webm",
                     avi = "video/avi")
  
  list(saver = saver, func = savers[[saver]], mime_type = mime_types[[saver]])
}

plot_ggplot_build <- function (b, newpage = is.null(vp), vp = NULL) 
{
  if (newpage) {
    grid::grid.newpage()
  }
  grDevices::recordGraphics(requireNamespace("ggplot2", quietly = TRUE), 
                            list(), getNamespace("ggplot2"))
  gtable <- ggplot_gtable(b)
  if (is.null(vp)) {
    grid::grid.draw(gtable)
  }
  else {
    if (is.character(vp)) 
      grid::seekViewport(vp)
    else grid::pushViewport(vp)
    grid::grid.draw(gtable)
    grid::upViewport()
  }
}

gg_animate_save <- function(g, filename = NULL, saver = NULL, ...) {
  # save to a temporary file if necessary
  if (is.null(filename)) {
    if (is.null(saver)) {
      filename <- gganimate::gganimate_tempfile(fileext = ".gif")
    } else {
      filename <- gganimate::gganimate_tempfile(fileext = paste0(".", saver))
    }
  }
  
  g$filename <- filename
  
  # figure out how it should be saved
  s <- animation_saver(saver, filename)
  
  # temporarily move to directory (may be current one, that's OK)
  # this helps with animation functions like saveGIF that work only in
  # current directory
  withr::with_dir(dirname(filename), {
    s$func(for (pl in g$plots) {
      plot_ggplot_build(pl)
    }, basename(filename), autobrowse = FALSE, ...)
  })
  
  if (!is.null(s$mime_type)) {
    # if it can be displayed in R, import it as an encoded string
    g$src <- base64enc::dataURI(file = filename, mime = s$mime_type)
    g$mime_type <- s$mime_type
  }
  g$saved <- TRUE
  g
}

