# function to suppress unnecessary warnings and messages generated by ggplot 
suppress_and_print <- function(x) suppressMessages(suppressWarnings(print(x)))

# make_param_list ------------------------------------------------------
# generate list of parameter names (formatted for shiny::selectInput)
.make_param_list <- function(object) {
  param_groups <- names(object@param_dims)
  choices <- list()
  ll <- length(object@param_dims)
  choices[1:ll] <- ""
  names(choices) <- param_groups
  for(i in 1:ll) {
    if (length(object@param_dims[[i]]) == 0) {
      choices[[i]] <- list(param_groups[i])
    }
    else {
      temp <- paste0(param_groups[i],"\\[")
      choices[[i]] <- object@param_names[grep(temp, object@param_names)]
    }
  }
  choices
}

# make_param_list_with_groups ------------------------------------------------------
# generate list of parameter names  and include parameter groups (formatted for shiny::selectInput)
.make_param_list_with_groups <- function(object, sort_j = FALSE) {
  choices <- list()
  param_groups <- names(object@param_dims)
  ll <- length(object@param_dims)
  LL <- sapply(1:ll, function(i) length(object@param_dims[[i]]))
  
  choices[1:ll] <- ""
  names(choices) <- param_groups
  for(i in 1:ll) {
    if (LL[i] == 0) {
      choices[[i]] <- list(param_groups[i])
    } else {
      group <- param_groups[i]
      temp <- paste0("^",group,"\\[")
      ch <- object@param_names[grep(temp, object@param_names)]
      
      #       toggle row/column major sorting so e.g. "beta[1,1], beta[1,2],
      #       beta[2,1], beta[2,2]" instead of "beta[1,1], beta[2,1], beta[1,2],
      #       beta[2,2]"
      if (sort_j == TRUE & LL[i] > 1) ch <- gtools::mixedsort(ch) 
      
      ch_out <- c(paste0(group,"_as_shiny_stan_group"), ch)
      names(ch_out) <- c(paste("ALL", group), ch)
      choices[[i]] <- ch_out
    }
  }
  
  choices
}

# update_params_with_groups -----------------------------------------------
# update parameter selection for multi-parameter plots
.update_params_with_groups <- function(params, all_param_names) {
  as_group <- grep("_as_shiny_stan_group", params)
  if (length(as_group) == 0) return(params)
  
  make_group <- function(group_name) {
    all_param_names[grep(paste0("^",group_name,"\\["), all_param_names)]
  }
  single_params <- params[-as_group]
  grouped_params <- params[as_group]
  groups <- gsub("_as_shiny_stan_group", "", grouped_params)
  groups <- sapply(groups, make_group)
  updated_params <- c(single_params, unlist(groups))
  updated_params
}


# ggplot theme elements to be used as needed  -----------------------------
blue_color <- "#346fa1"
theme <- function(...) ggplot2::theme(...)
transparent <- theme(panel.background = element_blank(), plot.background = element_blank())
axis_line_color <- blue_color
axis_color <- theme(axis.line = element_line(color = axis_line_color))
axis_labs <- theme(axis.title = element_text(face = "bold", size = 13))
title_txt <- theme(plot.title = element_text(face = "bold", size = 14))
fat_axis <- theme(axis.line.x = element_line(size = 3, color = axis_line_color), 
                  axis.line.y = element_line(size = 0.5, color = axis_line_color))
h_lines <- theme(panel.grid.major = element_line(size = 0.10, linetype = 3, color = "turquoise4"),
                 panel.grid.major.x = element_blank())
v_lines <- theme(panel.grid.major = element_line(size = 0.25, linetype = 3, color = "turquoise4"),
                 panel.grid.major.y = element_blank())
no_lgnd <- theme(legend.position = "none")
lgnd_bot <- theme(legend.position = "bottom", legend.background = element_blank())
lgnd_top <- theme(legend.position = "top", legend.background = element_blank())
lgnd_left <- theme(legend.position = "left", legend.background = element_blank())
lgnd_right <- theme(legend.position = "right", legend.background = element_blank())
no_yaxs <- theme(axis.line.y = element_blank(), axis.ticks.y = element_blank(), axis.text.y = element_blank())
strip_txt <- theme(strip.text = element_text(size = 12, face = "bold", color = "white"),
                   strip.background = element_rect(color = blue_color, fill = blue_color))


